#!/bin/bash
source ./credentials
source ./climethods

echo "deleting transcribeAudio Lambda function"
deleteTranscribeFunction
echo "deleting extractTranscript Lambda function"
deleteExtractFunction
echo "deleting Vocabulary for Transcribe service."
deleteTranscribeVocabulary
echo "deleting SNS Topic"
deleteTopic
echo "detaching IAM Policy from Role"
detachPolicy
echo "deleting IAM Role for Lambda function"
deleteRole
echo "deleting IAM Policy"
deletePolicy

rm -rf build/*
